FROM golang:alpine

RUN apk update && apk add git

RUN mkdir -p /go/src/github.com/byuoitav
ADD . /go/src/github.com/byuoitav/device-monitoring-microservice

WORKDIR /go/src/github.com/byuoitav/device-monitoring-microservice
RUN go get -d -v
RUN go install -v

CMD ["/go/bin/device-monitoring-microservice"]

EXPOSE 10000
